"""
Compliance Logger - Maintain regulatory-compliant audit trail

Logs all signals, decisions, and trades for regulatory compliance and defense.
"""

from typing import Dict, List, Optional, Any
from datetime import datetime, timezone
import json
import hashlib
import os
from dataclasses import dataclass, asdict


@dataclass
class ComplianceEntry:
    """Single compliance audit entry"""
    timestamp: str
    entry_id: str
    signal_id: str
    symbol: str
    signal_type: str
    action: str  # GENERATED, VALIDATED, APPROVED, REJECTED, EXECUTED
    data_sources: List[str]
    raw_data_urls: List[str]
    parsed_data: Dict
    decision_maker: str
    decision_reason: str
    compliance_checks: Dict[str, bool]
    position_size: float
    risk_level: str


class ComplianceDatabase:
    """Simple file-based compliance database"""
    
    def __init__(self, db_path: str = "compliance_audit.json"):
        """Initialize compliance database"""
        self.db_path = db_path
        self.entries = []
        
        # Load existing entries
        if os.path.exists(db_path):
            try:
                with open(db_path, 'r') as f:
                    data = json.load(f)
                    self.entries = data.get('entries', [])
            except Exception as e:
                print(f"[COMPLIANCE] Error loading database: {e}")
                self.entries = []
    
    def save(self, entry: ComplianceEntry):
        """Save entry to database"""
        # Convert to dict
        entry_dict = asdict(entry)
        
        # Add to entries
        self.entries.append(entry_dict)
        
        # Save to file
        try:
            with open(self.db_path, 'w') as f:
                json.dump({
                    'last_updated': datetime.now().isoformat(),
                    'total_entries': len(self.entries),
                    'entries': self.entries
                }, f, indent=2)
        except Exception as e:
            print(f"[COMPLIANCE] Error saving entry: {e}")
    
    def query(self, **filters) -> List[Dict]:
        """Query entries with filters"""
        results = []
        
        for entry in self.entries:
            match = True
            
            for key, value in filters.items():
                if key in entry and entry[key] != value:
                    match = False
                    break
            
            if match:
                results.append(entry)
        
        return results
    
    def get_recent(self, days: int = 30) -> List[Dict]:
        """Get recent entries"""
        cutoff = datetime.now().timestamp() - (days * 24 * 60 * 60)
        
        recent = []
        for entry in self.entries:
            entry_time = datetime.fromisoformat(entry['timestamp']).timestamp()
            if entry_time >= cutoff:
                recent.append(entry)
        
        return recent


class ComplianceLogger:
    """Maintain regulatory-compliant audit trail"""
    
    def __init__(self, db_path: str = None):
        """Initialize compliance logger"""
        self.db = ComplianceDatabase(db_path or "compliance/compliance_audit.json")
        
        # Ensure compliance directory exists
        os.makedirs("compliance", exist_ok=True)
        
        print("[COMPLIANCE] Audit trail initialized")
        print(f"[COMPLIANCE] Database: {self.db.db_path}")
    
    def log_signal_generation(self, signal: Dict, raw_data: Dict) -> str:
        """
        Log every signal with source data
        
        Args:
            signal: Generated signal
            raw_data: Raw source data
            
        Returns:
            Entry ID for tracking
        """
        # Generate unique ID
        entry_id = self._generate_id(signal)
        
        # Create compliance entry
        entry = ComplianceEntry(
            timestamp=datetime.now(timezone.utc).isoformat(),
            entry_id=entry_id,
            signal_id=signal.get('id', entry_id),
            symbol=signal.get('symbol', ''),
            signal_type=signal.get('type', 'UNKNOWN'),
            action='GENERATED',
            data_sources=self._extract_data_sources(raw_data),
            raw_data_urls=self._extract_urls(raw_data),
            parsed_data=signal,
            decision_maker='AI_SYSTEM',
            decision_reason='Signal generated by confluence analysis',
            compliance_checks=self._initial_compliance_checks(signal),
            position_size=0,  # Not determined yet
            risk_level='PENDING'
        )
        
        # Save to database
        self.db.save(entry)
        
        print(f"[COMPLIANCE] Signal logged: {signal.get('symbol')} - {entry_id}")
        return entry_id
    
    def log_validation(self, signal_id: str, validation_result: Dict, analyst: str = 'SYSTEM') -> str:
        """
        Log human validation decision
        
        Args:
            signal_id: Original signal ID
            validation_result: Validation outcome
            analyst: Who performed validation
            
        Returns:
            Entry ID
        """
        # Find original signal
        original = self.db.query(signal_id=signal_id)
        if not original:
            print(f"[COMPLIANCE] Warning: Signal {signal_id} not found")
            return None
        
        original = original[0]
        
        # Create validation entry
        entry_id = self._generate_id({'signal_id': signal_id, 'action': 'validation'})
        
        entry = ComplianceEntry(
            timestamp=datetime.now(timezone.utc).isoformat(),
            entry_id=entry_id,
            signal_id=signal_id,
            symbol=original['symbol'],
            signal_type=original['signal_type'],
            action='VALIDATED',
            data_sources=original['data_sources'],
            raw_data_urls=original['raw_data_urls'],
            parsed_data=validation_result,
            decision_maker=analyst,
            decision_reason=validation_result.get('recommendation', ''),
            compliance_checks=self._validation_compliance_checks(validation_result),
            position_size=validation_result.get('recommended_position_size', 0),
            risk_level=validation_result.get('risk_level', 'MEDIUM')
        )
        
        self.db.save(entry)
        
        print(f"[COMPLIANCE] Validation logged: {original['symbol']} - {validation_result.get('recommendation')}")
        return entry_id
    
    def log_trade_execution(self, signal_id: Dict, trade_details: Dict) -> str:
        """
        Log actual trade execution
        
        Args:
            signal_id: Signal identifier
            trade_details: Trade execution details
            
        Returns:
            Entry ID
        """
        entry_id = self._generate_id(trade_details)
        
        entry = ComplianceEntry(
            timestamp=datetime.now(timezone.utc).isoformat(),
            entry_id=entry_id,
            signal_id=signal_id.get('id', ''),
            symbol=trade_details.get('symbol', ''),
            signal_type=trade_details.get('signal_type', ''),
            action='EXECUTED',
            data_sources=['BROKER_EXECUTION'],
            raw_data_urls=[trade_details.get('confirmation_url', '')],
            parsed_data=trade_details,
            decision_maker=trade_details.get('trader', 'AUTO'),
            decision_reason=trade_details.get('execution_reason', ''),
            compliance_checks=self._trade_compliance_checks(trade_details),
            position_size=trade_details.get('position_size', 0),
            risk_level=trade_details.get('risk_level', 'MEDIUM')
        )
        
        self.db.save(entry)
        
        print(f"[COMPLIANCE] Trade executed: {trade_details.get('symbol')} - {trade_details.get('action')}")
        return entry_id
    
    def generate_compliance_report(self, start_date: datetime = None, end_date: datetime = None) -> Dict:
        """
        Generate compliance report for audit
        
        Args:
            start_date: Report start date
            end_date: Report end date
            
        Returns:
            Compliance report
        """
        # Get entries for period
        if start_date and end_date:
            entries = self._get_entries_by_date_range(start_date, end_date)
        else:
            entries = self.db.get_recent(days=90)  # Default last 90 days
        
        # Analyze entries
        analysis = {
            'period': {
                'start': start_date.isoformat() if start_date else None,
                'end': end_date.isoformat() if end_date else None,
                'total_entries': len(entries)
            },
            'summary': {
                'signals_generated': len([e for e in entries if e['action'] == 'GENERATED']),
                'signals_validated': len([e for e in entries if e['action'] == 'VALIDATED']),
                'signals_approved': len([e for e in entries if e['action'] == 'VALIDATED' and e['parsed_data'].get('recommendation') == 'APPROVED']),
                'trades_executed': len([e for e in entries if e['action'] == 'EXECUTED'])
            },
            'compliance_metrics': {
                'public_data_only': self._check_public_data_usage(entries),
                'position_sizes_compliant': self._check_position_sizes(entries),
                'mnpi_free': self._check_no_mnpi(entries),
                'documentation_complete': self._check_documentation(entries)
            },
            'risk_analysis': {
                'high_risk_trades': len([e for e in entries if e['risk_level'] == 'HIGH']),
                'concentration_risk': self._check_concentration(entries),
                'largest_position': self._get_largest_position(entries)
            }
        }
        
        return analysis
    
    def _generate_id(self, data: Dict) -> str:
        """Generate unique ID for entry"""
        content = json.dumps(data, sort_keys=True)
        return hashlib.sha256(content.encode()).hexdigest()[:16]
    
    def _extract_data_sources(self, raw_data: Dict) -> List[str]:
        """Extract list of data sources"""
        sources = []
        
        if 'form4_filings' in raw_data:
            sources.append('SEC_FORM4')
        if 'f13_filings' in raw_data:
            sources.append('SEC_13F')
        if 'analyst_data' in raw_data:
            sources.append('ANALYST_REPORTS')
        if 'options_data' in raw_data:
            sources.append('OPTIONS_CHAIN')
        if 'news_data' in raw_data:
            sources.append('NEWS_FEEDS')
        
        return sources or ['UNKNOWN']
    
    def _extract_urls(self, raw_data: Dict) -> List[str]:
        """Extract URLs from raw data"""
        urls = []
        
        for key, value in raw_data.items():
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict) and 'url' in item:
                        urls.append(item['url'])
            elif isinstance(value, str) and value.startswith('http'):
                urls.append(value)
        
        return urls
    
    def _initial_compliance_checks(self, signal: Dict) -> Dict[str, bool]:
        """Initial compliance checks for generated signal"""
        return {
            'public_data_only': True,  # Assuming all data is public
            'position_within_limits': True,  # Will be checked later
            'no_conflict_of_interest': True,
            'proper_documentation': bool(signal.get('id'))
        }
    
    def _validation_compliance_checks(self, validation: Dict) -> Dict[str, bool]:
        """Compliance checks for validation"""
        return {
            'human_review_completed': validation.get('recommendation') in ['APPROVED', 'REJECTED'],
            'risk_assessed': 'risk_level' in validation,
            'position_sized_appropriately': validation.get('total_score', 0) >= 0.6,
            'documentation_complete': len(validation.get('validation_items', {})) > 0
        }
    
    def _trade_compliance_checks(self, trade: Dict) -> Dict[str, bool]:
        """Compliance checks for trade execution"""
        return {
            'executed_within_limits': trade.get('position_size', 0) <= 0.02,  # 2% max
            'proper_confirmation': bool(trade.get('confirmation_id')),
            'timely_execution': True,  # Would check actual timing
            'best_execution': True  # Would check price vs market
        }
    
    def _get_entries_by_date_range(self, start: datetime, end: datetime) -> List[Dict]:
        """Get entries within date range"""
        results = []
        
        for entry in self.db.entries:
            entry_time = datetime.fromisoformat(entry['timestamp'])
            
            if start <= entry_time <= end:
                results.append(entry)
        
        return results
    
    def _check_public_data_usage(self, entries: List[Dict]) -> bool:
        """Check if only public data was used"""
        for entry in entries:
            sources = entry.get('data_sources', [])
            if 'INSIDER_CONTACT' in sources or 'MNPI' in sources:
                return False
        return True
    
    def _check_position_sizes(self, entries: List[Dict]) -> bool:
        """Check if all positions within limits"""
        for entry in entries:
            if entry.get('position_size', 0) > 0.02:  # 2% limit
                return False
        return True
    
    def _check_no_mnpi(self, entries: List[Dict]) -> bool:
        """Check no material non-public information used"""
        # Would check timestamps vs public release dates
        return True  # Assuming compliant
    
    def _check_documentation(self, entries: List[Dict]) -> bool:
        """Check all entries have proper documentation"""
        for entry in entries:
            if not entry.get('raw_data_urls') or not entry.get('parsed_data'):
                return False
        return True
    
    def _check_concentration(self, entries: List[Dict]) -> Dict:
        """Check concentration risk"""
        positions = {}
        
        for entry in entries:
            if entry['action'] == 'EXECUTED':
                symbol = entry['symbol']
                size = entry.get('position_size', 0)
                positions[symbol] = positions.get(symbol, 0) + size
        
        max_concentration = max(positions.values()) if positions else 0
        
        return {
            'max_single_position': max_concentration,
            'within_limits': max_concentration <= 0.05  # 5% max per position
        }
    
    def _get_largest_position(self, entries: List[Dict]) -> float:
        """Get largest position size"""
        max_size = 0
        
        for entry in entries:
            if entry['action'] == 'EXECUTED':
                max_size = max(max_size, entry.get('position_size', 0))
        
        return max_size


# Example usage
if __name__ == "__main__":
    logger = ComplianceLogger()
    
    # Log a signal
    signal = {
        'id': 'test_signal_001',
        'symbol': 'TEST',
        'type': 'CONFLUENCE',
        'confidence': 0.85
    }
    
    raw_data = {
        'form4_filings': [{'url': 'http://sec.gov/...'}],
        'f13_filings': [{'url': 'http://sec.gov/...'}]
    }
    
    entry_id = logger.log_signal_generation(signal, raw_data)
    print(f"Logged signal with ID: {entry_id}")
